### ISSUE TITLE
Catch SimpLL exceptions when running as a library

### ISSUE THREAD

**Issue by viktormalik** [viktormalik/diffkemp#240]
When SimpLL runs as a library (via FFI) and it throws an exception, DiffKemp fails without providing any useful information. The exception should be caught in the FFI layer and handled properly.

**Comment by lenticularis39** [comment]
LLVM code shouldn't throw exceptions, see https://llvm.org/docs/CodingStandards.html#do-not-use-rtti-or-exceptions.

The actual problem is LLVM segfaulting when loading invalid modules and SimpLL segfaulting in some cases (e.g. debug info not present). The latter is a SimpLL bug and should be fixed, the former could be fixed by checking the modules beforehand, at the cost of some performance.
