### ISSUE TITLE
Change in function return type from void to non-void should not be a difference

### ISSUE THREAD

**Issue by viktormalik** [viktormalik/diffkemp#33]
This applies to cases when the only difference are returns from the new function. In the old version, no one could check the return value, so changing the return type cannot break anything.
This occurs for KABI whitelist symbol `__napi_complete`.

**Comment by viktormalik** [comment]
We could detect this situation, change the new function's return type to void and remove `ret` instructions.

**Comment by lenticularis39** [comment]
After looking more closely at the reported difference, I think that the functions are actually semantically different. The code that causes the difference in the C source code, i.e.
```c
if (unlikely(test_bit(NAPI_STATE_IN_BUSY_POLL, &n->state)))
    return false;
```
occurs on the very beginning of the function, therefore the effect is not only the return value of the function changes (this is the thing that I am trying to avoid being compared as unequal), but also the function exists at another line (i.e. it doesn't do anything, unlike the case when the condition is false).

Nevertheless the fix of the problem described in this issue is ready - the comparison of `__napi_complete` will be fixed by smart resolution of if conditions.

**Comment by viktormalik** [comment]
The proposed fix leads to a bug in certain situations, due to broken debugging information.
The bug occurs e.g. for KABI symbol `napi_complete` between the 3.10.0-693.el7 and the 3.10.0-862.el7 kernels.
